
-- Action items generated by AI, with progress tracking
CREATE TABLE public.action_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country_code TEXT NOT NULL DEFAULT 'NG',
  timeline TEXT NOT NULL CHECK (timeline IN ('short_term', 'medium_term', 'long_term')),
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'off_track')),
  priority INTEGER NOT NULL DEFAULT 2 CHECK (priority BETWEEN 1 AND 3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  due_date TIMESTAMPTZ,
  notes TEXT,
  -- Future: user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
  created_by TEXT DEFAULT 'system'
);

-- Index for common queries
CREATE INDEX idx_action_items_country ON public.action_items(country_code);
CREATE INDEX idx_action_items_status ON public.action_items(status);
CREATE INDEX idx_action_items_timeline ON public.action_items(timeline);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER action_items_updated_at
  BEFORE UPDATE ON public.action_items
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- Public access for now (no auth); will add RLS when auth is added
ALTER TABLE public.action_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON public.action_items
  FOR SELECT USING (true);

CREATE POLICY "Public insert access" ON public.action_items
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Public update access" ON public.action_items
  FOR UPDATE USING (true);

CREATE POLICY "Public delete access" ON public.action_items
  FOR DELETE USING (true);

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.action_items;
